[package]
name = "ultracomb"
version = "0.4.0"
edition = "2021"
authors = ["Wasaka <your@email.com>"]
license = "GPL-3.0-or-later"
homepage = "https://youtu.be/dQw4w9WgXcQ"
description = "Ultracomb is a combination of flanging and phasing with continous movement in the frequency spectrum. The rendering pipeline for this was described and named by artist Au5."

[workspace]
members = ["xtask"]

[lib]
crate-type = ["cdylib"]

[dependencies]
# Remove the `assert_process_allocs` feature to allow allocations on the audio
# thread in debug builds.
nice-plug = { git = "https://codeberg.org/BillyDM/nice-plug.git", rev = "7e7f63049dc2250fa755bc45acb1badce8c7bd4c" }
vizia_plug = { git = "https://github.com/vizia/vizia-plug.git", rev = "9d3f4175b5afad9b2e28c2d7a7faad25379ed4a2" }
bitflags = "2.13.0"

[profile.release]
lto = "thin"
strip = "symbols"

[profile.profiling]
inherits = "release"
debug = true
strip = "none"
